### ISSUE TITLE
Crashes when starting up a world.

### ISSUE THREAD

**Issue by ghost** [funniray/Mixer#9]
I'm trying to add the mixer interactive 1.12.2 to the FTB Ultimate pack and receiving problems.
![image](https://user-images.githubusercontent.com/51179083/64061367-acd8bf00-cbd1-11e9-8177-31abfa9eb1eb.png)
[crash-2019-08-31_09.23.58-server.txt](https://github.com/funniray/Mixer/files/3562214/crash-2019-08-31_09.23.58-server.txt)

**Comment by funniray** [comment]
This is because you were using the forge 1.13.2 version, which uses an entirely different command system. If you still want to use this plugin, use the sponge version or 1.12.2 forge version. (Forge version are mostly just for me to test new features easily)
